name: "Get Branch Name"
author: Luke Swanson
description: "This action retrieves the first n characters of a branch name, ignoring any branch prefixes."
branding:
  icon: 'git-branch'
  color: 'blue'
inputs:
  n:
    description: "The number of characters to retrieve"
    required: false
    default: 10
  separator:
    description: "The separator used to split branch prefixes"
    required: false
    default: "/"
  debug:
    description: "Whether to include extra debug prints to check the input and output"
    required: false
    default: "false"
  shell:
    description: "The shell to use for executing steps"
    required: false
    default: "bash"
outputs:
  branch-name:
    description: "The first n characters of the branch name"
    value: ${{ steps.get_branch.outputs.branch_name }}
runs:
  using: "composite"
  steps:
    - name: Announce initial branch name
      if: ${{ inputs.debug == "true" }}
      run: echo "Splitting " ${{ github.ref_name }}
      shell: ${{ inputs.shell }}
    - name: Get Branch Name
      id: get_branch
      run: |
        BRANCH=$(echo "${{ github.ref_name }}" | awk '{ print(substr(arr[split($0, arr, "/")], 1, 10)) }')
         echo "branch_name=$BRANCH" >> "$GITHUB_OUTPUT"
      shell: ${{ inputs.shell }}
    - name: Announce extracted branch name
      if: ${{ inputs.debug == "true" }}
      run: echo "After split, branch is ${{ steps.get_branch.outputs.branch_name }}"
      shell: ${{ inputs.shell }}
